name: pIIpet-p20
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gmt=6.1.1
  - pygmt=0.3.0
  - jupyterlab=3.0.7
  - jupyter-offlinenotebook=0.2.1
  - pandas=1.2.2
  - openpyxl
  
  